---
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lhd
    username: root
    password: 
    
  http:
      multipart:
         max-file-size: 30Mb
  jpa:
    hibernate.ddl-auto: update
    show-sql: false 
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:  
     host: mail.lhdconsult.org
     port: 2525
     username: contact@lhdconsult.org
     password: 711380Dm
     properties:
         mail:
            smtp:
              auth: true
              starttls:
                enable: true
    