---
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lhd
    username: root
    password: 1234
    
  jpa:
    hibernate.ddl-auto: update
    show-sql: false 
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:  
     host: mail.lhdconsult.org
     port: 2525
     properties:
         mail:
            smtp:
              auth: true
              starttls:
                enable: true
     