---
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username: 
    password: 
    
  http:
      multipart:
         max-file-size: 30Mb
  jpa:
    hibernate.ddl-auto: none
    show-sql: false 
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:  
     host: mail.lhdconsult.org
     port: 2525
     properties:
         mail:
            smtp:
              auth: true
              starttls:
                enable: true
    