---
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/lhd
    username: root
=======
    url:
    username: 
>>>>>>> cc3dd525700ba8365b46ddabfb364515184ad6da
    password: 
    
  http:
      multipart:
         max-file-size: 30Mb
  jpa:
    hibernate.ddl-auto: update
    show-sql: false 
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:  
     host: mail.lhdconsult.org
     port: 2525
     properties:
         mail:
            smtp:
              auth: true
              starttls:
                enable: true
    